#!/usr/bin/env python3
"""
Example usage of the generalized multi-agent system

This script demonstrates how the new FrontendDesignAgentGraph can automatically
detect and work with any number of agents using the agent1, agent2, etc. naming convention.
"""

import asyncio
import tempfile
from typing import Dict, Any

# Import the generalized multi-agent system
from pettingllms.agentgpraphs.design_human_interact.agent_collaboration_graph import FrontendDesignAgentGraph
from pettingllms.agentgpraphs.design_human_interact.websight_env import WebEnv


class MockAgent:
    """Mock agent for demonstration purposes"""
    
    def __init__(self, agent_type: str):
        self.agent_type = agent_type
        self.chat_completions = []
        
    def reset(self):
        """Reset agent state"""
        self.chat_completions = []
        
    def update_from_env(self, observation, reward, done, info):
        """Update agent with environment observation"""
        message = {
            "role": "user", 
            "content": f"Agent {self.agent_type}: received observation with reward {reward}"
        }
        self.chat_completions.append(message)
        
    def update_from_model(self, response):
        """Update agent with model response"""
        message = {
            "role": "assistant",
            "content": response
        }
        self.chat_completions.append(message)
        
        # Return a mock action
        class MockAction:
            def __init__(self, action_text):
                self.action = action_text
                
        return MockAction(f"Action from {self.agent_type} agent")
        
    def get_generated_html(self):
        """Mock HTML generation for code agents"""
        return f"<html><body>Generated by {self.agent_type}</body></html>"
        
    def get_suggestions_summary(self):
        """Mock suggestions for visual agents"""
        return f"Visual suggestions from {self.agent_type} agent"


class ExtendedFrontendDesignAgentGraph(FrontendDesignAgentGraph):
    """Extended version that supports additional agent types"""
    
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        
        # Add additional agents for demonstration
        self.planning_agent = MockAgent("planning")
        self.testing_agent = MockAgent("testing")
        self.review_agent = MockAgent("review")
    
    def _get_agent_client_method(self, original_agent_name: str):
        """Override to support additional agent types"""
        if 'code' in original_agent_name.lower():
            return self.client.get_code_response
        elif 'visual' in original_agent_name.lower():
            return self.client.get_visual_response
        elif 'planning' in original_agent_name.lower():
            return self.client.get_code_response  # Use code response for planning
        elif 'testing' in original_agent_name.lower():
            return self.client.get_visual_response  # Use visual response for testing
        elif 'review' in original_agent_name.lower():
            return self.client.get_code_response  # Use code response for review
        else:
            # Default to code response for unknown agent types
            return self.client.get_code_response


def create_mock_environment():
    """Create a mock environment for testing"""
    mock_sample = {
        "task_id": "test_task_001",
        "problem_description": "Create a responsive navigation bar with dropdown menus",
        "ground_truth": "<html><body><nav>Navigation</nav></body></html>"
    }
    return mock_sample


async def demonstrate_multi_agent_system():
    """Demonstrate the generalized multi-agent system"""
    print("🚀 Demonstrating Generalized Multi-Agent System")
    print("=" * 60)
    
    # Create the generalized agent graph
    agent_graph = ExtendedFrontendDesignAgentGraph(
        hostname="localhost",
        code_port=8000,
        visual_port=8001,
        max_iterations=2,
        temp_path=tempfile.gettempdir()
    )
    
    # Create mock environment
    mock_sample = create_mock_environment()
    env = WebEnv(task=mock_sample, max_turns=4, temp_path=tempfile.gettempdir())
    
    # Get initial observation
    obs, _ = env.reset()
    
    print(f"📝 Task: {mock_sample['problem_description']}")
    print(f"🎯 Task ID: {mock_sample['task_id']}")
    
    try:
        # Run the multi-agent loop
        print("\n🔄 Running multi-agent loop...")
        model_update_data = await agent_graph.multi_agent_loop(
            env=env,
            initial_observation=obs,
            max_steps=2,
            application_id="demo_001"
        )
        
        # Display results
        print("\n📊 Results Summary:")
        print("=" * 40)
        
        collaboration_data = model_update_data.get("collaboration_data", {})
        print(f"🤖 Total agents detected: {collaboration_data.get('agent_count', 0)}")
        print(f"📝 Agent names: {collaboration_data.get('agent_names', [])}")
        print(f"🔄 Total iterations: {len(collaboration_data.get('iterations', []))}")
        print(f"✅ Task completion: {collaboration_data.get('task_completion', False)}")
        
        # Display individual agent data
        print("\n🤖 Individual Agent Results:")
        print("-" * 40)
        
        for agent_name, agent_data in model_update_data.items():
            if agent_name != "collaboration_data":
                print(f"\n{agent_name.upper()} ({agent_data.get('original_name', 'unknown')}):")
                print(f"  📈 Total reward: {agent_data.get('total_reward', 0)}")
                print(f"  ✅ Success: {agent_data.get('success', False)}")
                print(f"  📊 Actions taken: {len(agent_data.get('actions', []))}")
                print(f"  ⏱️  Execution time: {agent_data.get('execution_time', {}).get('total_time', 0):.2f}s")
                print(f"  🔚 Termination: {agent_data.get('termination_reason', 'N/A')}")
        
        # Display step-by-step breakdown
        print("\n📝 Step-by-Step Breakdown:")
        print("-" * 40)
        
        for i, iteration in enumerate(collaboration_data.get('iterations', []), 1):
            print(f"\nStep {i}:")
            agent_actions = iteration.get('agent_actions', {})
            for agent_name, action_data in agent_actions.items():
                action_type = action_data.get('action_type', 'unknown')
                execution_time = action_data.get('execution_time', 0)
                print(f"  {agent_name}: {action_type} action ({execution_time:.3f}s)")
        
        print("\n✨ Demo completed successfully!")
        
    except Exception as e:
        print(f"❌ Error during demonstration: {e}")
        import traceback
        traceback.print_exc()
    
    finally:
        # Cleanup
        env.cleanup()
        agent_graph.cleanup()


def show_data_structure_example():
    """Show an example of the output data structure"""
    print("\n📋 Expected Output Data Structure:")
    print("=" * 50)
    
    example_structure = {
        "agent1": {
            "original_name": "code_agent",
            "trajectory_steps": ["List of trajectory steps"],
            "rewards": [0.5, 0.8],
            "observations": ["List of observations"],
            "actions": ["List of actions"],
            "prompts": ["List of prompts"],
            "responses": ["List of responses"],
            "total_reward": 1.3,
            "success": True,
            "termination_reason": "TASK_COMPLETED",
            "execution_time": {"llm_time": 2.5, "env_time": 1.2, "total_time": 3.7}
        },
        "agent2": {
            "original_name": "visual_agent",
            "trajectory_steps": ["List of trajectory steps"],
            "rewards": [0.3, 0.7],
            "observations": ["List of observations"],
            "actions": ["List of actions"],
            "prompts": ["List of prompts"],
            "responses": ["List of responses"],
            "total_reward": 1.0,
            "success": True,
            "termination_reason": "TASK_COMPLETED",
            "execution_time": {"llm_time": 2.5, "env_time": 1.2, "total_time": 3.7}
        },
        "agent3": {
            "original_name": "planning_agent",
            # ... similar structure
        },
        "collaboration_data": {
            "iterations": ["List of iteration details"],
            "final_state": {"final_observation": {}, "total_steps": 3},
            "task_completion": True,
            "agent_count": 3,
            "agent_names": ["agent1", "agent2", "agent3"]
        }
    }
    
    import json
    print(json.dumps(example_structure, indent=2))


if __name__ == "__main__":
    print("🎯 Generalized Multi-Agent System Demonstration")
    print("📘 This script shows how the system automatically detects agents")
    print("🔧 and creates standardized agent1, agent2, etc. naming")
    print()
    
    # Show expected data structure
    show_data_structure_example()
    
    # Run the demonstration
    asyncio.run(demonstrate_multi_agent_system()) 