#!/bin/bash
# 设置训练环境变量

export CUDA_VISIBLE_DEVICES="0"
export TRITON_CACHE_DIR="/tmp/triton_cache"
export TRITON_DEBUG="1"
export RAY_EXPERIMENTAL_NOSET_CUDA_VISIBLE_DEVICES="1"
export SGLANG_DISABLE_TP_MEMORY_INBALANCE_CHECK="true"
export SGLANG_BLOCK_NONZERO_RANK_CHILDREN="0"

echo '环境变量已设置'
